// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDUMte9CTLix-xXZCTsyCK_z6Evd1rmk',
    appId: '1:66394550901:web:c7d6434619719d16c9be3c',
    messagingSenderId: '66394550901',
    projectId: 'fread-e85c0',
    authDomain: 'fread-e85c0.firebaseapp.com',
    databaseURL: 'https://fread-e85c0-default-rtdb.firebaseio.com',
    storageBucket: 'fread-e85c0.appspot.com',
    measurementId: 'G-BJT6C6808L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoo-QVKA2UQBuIdokZnBBUcdyeWHnBMQ',
    appId: '1:66394550901:android:fcbcbc3b0e6bfeeac9be3c',
    messagingSenderId: '66394550901',
    projectId: 'fread-e85c0',
    databaseURL: 'https://fread-e85c0-default-rtdb.firebaseio.com',
    storageBucket: 'fread-e85c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQ1qaGpNJJCAUOvn4OlBnEqJzsm8Wzvw',
    appId: '1:66394550901:ios:68796a2df314f0dfc9be3c',
    messagingSenderId: '66394550901',
    projectId: 'fread-e85c0',
    databaseURL: 'https://fread-e85c0-default-rtdb.firebaseio.com',
    storageBucket: 'fread-e85c0.appspot.com',
    iosClientId: '66394550901-8hg3r4mljvj51cbl8lmbi2pihv6muli5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQ1qaGpNJJCAUOvn4OlBnEqJzsm8Wzvw',
    appId: '1:66394550901:ios:68796a2df314f0dfc9be3c',
    messagingSenderId: '66394550901',
    projectId: 'fread-e85c0',
    databaseURL: 'https://fread-e85c0-default-rtdb.firebaseio.com',
    storageBucket: 'fread-e85c0.appspot.com',
    iosClientId: '66394550901-8hg3r4mljvj51cbl8lmbi2pihv6muli5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fread',
  );
}
