name: fread
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Text
  auto_size_text: ^3.0.0
  sizer: ^2.0.15
  easy_localization: ^3.0.1

  # Splash Screen
  introduction_screen: ^3.0.2
  flutter_native_splash: ^2.2.2
  
  #firabase
  
flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash/splash_400.png"
  color_dark: "#2c3e43"
  image_dark: "assets/splash/splash_400.png"
  android: true
  ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/auth/welcome.png
    - assets/images/avatars/
    - assets/images/illustrator/
    - assets/images/books/
    - assets/translations/
    - assets/splash/flutter_native_splash.yaml

  fonts:
    - family: SF_PRO
      fonts:
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYTHINITALIC.OTF
          style: italic
          weight: 200
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
          weight: 300
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 400
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic
          weight: 500
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
          weight: 600
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
          weight: 700
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYREGULAR.OTF
          style: normal
          weight: 400
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYMEDIUM.OTF
          style: normal
          weight: 500
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYSEMIBOLD.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SF_PRO/SFPRODISPLAYBOLD.OTF
          style: normal
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.OTF
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.otf
          style: normal
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.otf
          style: normal
          weight: 800
 