name: fread
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Text
  auto_size_text: ^3.0.0
  sizer: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/auth/welcome.png
    - assets/icons/

  fonts:
    - family: SF_PRO
      fonts:
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          style: italic
          weight: 200
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
          weight: 300
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          style: normal
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          style: normal
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLD.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          style: normal
          weight: 700
